export const REQUEST_SERVICES = "REQUEST_SERVICES";
export const FETCH_SERVICES = "FETCH_SERVICES";
export const FETCH_SERVICE = "FETCH_SERVICE";
export const ADD_SERVICE = "ADD_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const UPDATE_SERVICE_FILTERS = "UPDATE_SERVICE_FILTERS";

export const REQUEST_WORKERS = "REQUEST_WORKERS";
export const RESPONSE_WORKERS = "RESPONSE_WORKERS";
export const FETCH_WORKERS = "FETCH_WORKERS";
export const ADD_WORKER = "ADD_WORKER";
export const EDIT_WORKER = "EDIT_WORKER";
export const DELETE_WORKER = "DELETE_WORKER";

export const REQUEST = "REQUEST";
export const SET_YEAR_FILTER = "SET_YEAR_FILTER";
export const FETCH_SERVICES_YEAR = "FETCH_SERVICES_YEAR";
export const SET_YEAR_MONTH_FILTER = "SET_YEAR_MONTH_FILTER";
export const FETCH_SERVICES_YEAR_MONTH = "FETCH_SERVICES_YEAR_MONTH";

export const FETCH_PAYMENTS = "FETCH_PAYMENTS";
export const FETCH_UNPAID_SERVICES = "FETCH_UNPAID_SERVICES";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
